// vue-todolist/src/components/Formaddtodo.vue
<template>
<div class="form-inline">
    <div class="form-group">
        <input type="text" v-model="todoText" class="form-control mx-sm-3" placeholder="i want to do ..."/>
        <button class="btn btn-primary" @click="addTodo">add</button>
    </div>
</div>    
</template>

<script>
export default {
    data() {
        return {
            todoText : ''
        }
    },
    methods: {
        addTodo() {
            console.log(this.todoText);
            this.$emit('add-todo' , this.todoText)
            this.todoText = ''
        }
    },
}
</script>

// react-todolist/src/Components/Todo/FormAddTodo.js
import { useState } from "react";
function FormAddTodo(props) {
   const [text, setText] = useState('');
   let formHandler = (e) => {
        e.preventDefault();
       props.add(text);
       setText('');
    }


    let inputHandler = (e) => setText(e.target.value);


    return (
        <form className="form-inline" onSubmit={formHandler}>
            <div className="form-group d-flex">
                <input type="text" className="form-control mx-sm-3" onChange={inputHandler} placeholder="i want to do ..." value={text} />
                <button type="submit" className="btn btn-primary">add</button>
            </div>
        </form>
    )
}

export default FormAddTodo;
